version: 2

group_defaults:
  author_approval:
      auto: true
  approve_by_comment:
    enabled: true
    approve_regex: '(^Approved|OK|Ok|ok)'

groups:
  general:
    conditions:
      files:
        exclude:
          - CACAO2018/src/abstraction/eq1DIST/*
          - CACAO2018/src/abstraction/eq2PROD/*
          - CACAO2018/src/abstraction/eq3PROD/*
          - CACAO2018/src/abstraction/eq4TRAN/*
          - CACAO2018/src/abstraction/eq5TRAN/*
          - CACAO2018/src/abstraction/eq6DIST/*
          - CACAO2018/src/abstraction/eq7TRAN/*
    required: 1
    reset_on_push:
      enabled: false
    users:
    - massimotisi

  equipe2-producteur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq2PROD/*
    required: 1
    users: 
      - AgatheChevalier

  equipe3-producteur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq3PROD/*
    required: 1
    users: 
      - CouvratClaire

  equipe4-transformateur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq4TRAN/*
    required: 1
    users: 
      - Carlivoix

  equipe5-transformateur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq5TRAN/*
    required: 1
    users: 
      - ThomasSchillaci

  equipe7-transformateur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq7TRAN/*
    required: 1
    users: 
      - leo80250

  equipe1-distributeur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq1DIST/*
    required: 1
    users: 
      - elisagm

  equipe6-distributeur:
    conditions:
      files:
        - CACAO2018/src/abstraction/eq6DIST/*
    required: 1
    users: 
      - leo-petitjean
